name: Dockerfile Debian Buster - Latest CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Docker check
      run: docker version

    - name: Files Check
      run: sudo apt update && sudo apt install -y tree && tree && ls -lhat

    - name: Build Docker image
      run: docker build . --file 7.4/buster/Dockerfile --tag docker.pkg.github.com/mohsenmottaghi/php-fpm-zts/php-fpm-zts:latest

    - name: Push Docker image
      run: |
        docker login docker.pkg.github.com --username mohsenmottaghi -p ${{ secrets.GITHUB_PACKAGES }}
        docker push docker.pkg.github.com/mohsenmottaghi/php-fpm-zts/php-fpm-zts:latest